### ISSUE TITLE
Join NeoBOTS on Slack

### ISSUE THREAD

**Issue by buddybu** [neobots2903/Steamworks#1]
@neobots2903/programmers 

Slack channel is open for discussion of ideas, get updates whenever github is updated, or just general conversation.  Send me an email and I will send you the invitiation to join.

budburnham at gmail dot com

**Comment by LemonJustice** [comment]
I would like to be part of the chat!  -Liam Kikuchi(Lemon)

**Comment by CrypticStick** [comment]
Discord now, haha
